[[sections]]
length = 0
[sections.syringe_parameters]
G = {reactor_concentration = 1}
ATP = {reactor_concentration = 4.1166}
ADP = {reactor_concentration = 1.95}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 9000
[sections.syringe_parameters]
G = {reactor_concentration = 1}
ATP = {reactor_concentration = 4.1166}
ADP = {reactor_concentration = 1.95}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.4}
ATP = {reactor_concentration = 7.15}
ADP = {reactor_concentration = 1.95}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 2.9}
ATP = {reactor_concentration = 1.7333}
ADP = {reactor_concentration = 1.95}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 2.9}
ATP = {reactor_concentration = 2.8166}
ADP = {reactor_concentration = 0.75}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 2.6}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 0.75}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.5}
ATP = {reactor_concentration = 5.6333}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.5}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 3.9}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.5}
ATP = {reactor_concentration = 1.0833}
ADP = {reactor_concentration = 1.2}
NAD = {reactor_concentration = 5.85}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.5}
ATP = {reactor_concentration = 1.0833}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 5.85}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.5}
ATP = {reactor_concentration = 1.0833}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 5.85}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.5}
ATP = {reactor_concentration = 3.0333}
ADP = {reactor_concentration = 3.15}
NAD = {reactor_concentration = 3.15}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 2.1}
ATP = {reactor_concentration = 2.6}
ADP = {reactor_concentration = 0.75}
NAD = {reactor_concentration = 3.6}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.8}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 1.8}
NAD = {reactor_concentration = 1.125}
[sections.total_flow]
total_flow = 300
phosphate_flow = 7.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.2}
ATP = {reactor_concentration = 3.77}
ADP = {reactor_concentration = 1.08}
NAD = {reactor_concentration = 4.455}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 3.77}
ADP = {reactor_concentration = 1.98}
NAD = {reactor_concentration = 4.455}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 3.77}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 2.16}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.08}
ATP = {reactor_concentration = 1.04}
ADP = {reactor_concentration = 2.34}
NAD = {reactor_concentration = 3.51}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.08}
ATP = {reactor_concentration = 1.04}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 3.51}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.08}
ATP = {reactor_concentration = 2.86}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 3.51}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.08}
ATP = {reactor_concentration = 0.65}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 2.835}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.26}
ATP = {reactor_concentration = 3.12}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 2.835}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 5.72}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 4.05}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 5.72}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 4.05}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.8}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 0.45}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 3.6}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 3.12}
ADP = {reactor_concentration = 3.24}
NAD = {reactor_concentration = 3.78}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.08}
ATP = {reactor_concentration = 4.68}
ADP = {reactor_concentration = 2.52}
NAD = {reactor_concentration = 1.35}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.44}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 0.675}
[sections.total_flow]
total_flow = 500
phosphate_flow = 12.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.1143}
ATP = {reactor_concentration = 4.4571}
ADP = {reactor_concentration = 2.1214}
NAD = {reactor_concentration = 2.5071}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.2}
ATP = {reactor_concentration = 4.4571}
ADP = {reactor_concentration = 1.4143}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.3714}
ATP = {reactor_concentration = 4.4571}
ADP = {reactor_concentration = 1.2857}
NAD = {reactor_concentration = 3.0857}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.0286}
ATP = {reactor_concentration = 0.4643}
ADP = {reactor_concentration = 0.9643}
NAD = {reactor_concentration = 0.4821}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.0286}
ATP = {reactor_concentration = 4.4571}
ADP = {reactor_concentration = 0.3214}
NAD = {reactor_concentration = 0.4821}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.2}
ATP = {reactor_concentration = 3.3428}
ADP = {reactor_concentration = 0.3214}
NAD = {reactor_concentration = 0.4821}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 1.8}
ATP = {reactor_concentration = 0.4643}
ADP = {reactor_concentration = 2.3143}
NAD = {reactor_concentration = 4.6286}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 0.2143}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 1.5428}
NAD = {reactor_concentration = 1.4464}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 0.2143}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 1.5428}
NAD = {reactor_concentration = 4.05}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 0.2143}
ATP = {reactor_concentration = 3.9}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 0.4821}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 2.0571}
ATP = {reactor_concentration = 2.2286}
ADP = {reactor_concentration = 3.0857}
NAD = {reactor_concentration = 1.4464}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 600
[sections.syringe_parameters]
G = {reactor_concentration = 2.5714}
ATP = {reactor_concentration = 0.4643}
ADP = {reactor_concentration = 2.5714}
NAD = {reactor_concentration = 1.4464}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 2.7857}
ATP = {reactor_concentration = 0.4643}
ADP = {reactor_concentration = 0.3214}
NAD = {reactor_concentration = 0.4821}
[sections.total_flow]
total_flow = 700
phosphate_flow = 17.5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 3}
ATP = {reactor_concentration = 1.625}
ADP = {reactor_concentration = 1.125}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.75}
ATP = {reactor_concentration = 4.875}
ADP = {reactor_concentration = 2.25}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.05}
ATP = {reactor_concentration = 2.925}
ADP = {reactor_concentration = 3.15}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.9}
ATP = {reactor_concentration = 1.95}
ADP = {reactor_concentration = 2.475}
NAD = {reactor_concentration = 3.7125}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.05}
ATP = {reactor_concentration = 1.625}
ADP = {reactor_concentration = 2.475}
NAD = {reactor_concentration = 3.7125}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.95}
ATP = {reactor_concentration = 1.625}
ADP = {reactor_concentration = 1.8}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.05}
ATP = {reactor_concentration = 3.575}
ADP = {reactor_concentration = 2.475}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 3}
ATP = {reactor_concentration = 1.625}
ADP = {reactor_concentration = 1.125}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.8}
ATP = {reactor_concentration = 1.625}
ADP = {reactor_concentration = 2.7}
NAD = {reactor_concentration = 1.6875}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 1.2}
ATP = {reactor_concentration = 2.6}
ADP = {reactor_concentration = 1.8}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 900
[sections.syringe_parameters]
G = {reactor_concentration = 0.75}
ATP = {reactor_concentration = 2.6}
ADP = {reactor_concentration = 1.8}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5

[[sections]]
length = 3600
[sections.syringe_parameters]
G = {reactor_concentration = 0.3}
ATP = {reactor_concentration = 2.6}
ADP = {reactor_concentration = 1.8}
NAD = {reactor_concentration = 2.7}
[sections.total_flow]
total_flow = 200
phosphate_flow = 5
